name: CI/CD Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: $
  {{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no
  ec2-user@${{ secrets.HOST }} << 'EOF'
            cd /home/ec2-user/devops
            git pull origin master
          EOF
